name: habitude_app
description: "A new Flutter project."

publish_to: 'none' # Remova esta linha se quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Altere seu SDK para ser mais abrangente, ou mantenha ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  isar: ^3.1.0 # Certifique-se que esteja nesta versão
  isar_flutter_libs: ^3.1.0 # Certifique-se que esteja nesta versão
  path_provider: ^2.1.5
  flutter_slidable: ^4.0.0
  flutter_heatmap_calendar: ^1.0.5
  intl: ^0.20.2
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0 # Certifique-se que esteja nesta versão
  build_runner: any


flutter:
  uses-material-design: true